default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username:
  password:

development:
  <<: *default
  database: menuapp_dev

test:
  <<: *default
  database: menuapp_test

production:
  <<: *default
  database: menuapp_production
